# Generated by Django 5.2.8 on 2026-01-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100)),
                ('item_price', models.IntegerField()),
                ('item_description', models.TextField()),
                ('item_image', models.ImageField(upload_to='')),
                ('item_quantity', models.IntegerField()),
            ],
        ),
    ]
