# Generated by Django 5.2.8 on 2026-02-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concatenatio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_types',
            field=models.CharField(choices=[('Бр', 'Брелоки'), ('Откр', 'Открытки'), ('Ст', 'Стикеры'), ('Блк', 'Блокноты'), ('Знч', 'Значки'), ('Прч', 'Прочее')], default=35, max_length=100),
            preserve_default=False,
        ),
    ]
