# Generated by Django 5.2.8 on 2026-02-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concatenatio_app', '0002_item_item_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image_2',
            field=models.ImageField(default='none', upload_to=''),
        ),
    ]
