# Generated by Django 5.2.8 on 2026-02-21 07:46

import concatenatio_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concatenatio_app', '0003_item_item_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='none', upload_to=concatenatio_app.models.Item.user_directory_path),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image_2',
            field=models.ImageField(default='none', upload_to=concatenatio_app.models.Item.user_directory_path),
        ),
    ]
